### PR TITLE
Refs fixes 5

### PR DESCRIPTION
**Pull request by ChALkeR**
Ref resolution logic is mostly rewritten here.
We can say that `$ref` works now.

`$anchor` support and more testing is needed though (will come separately).

### CODE REVIEW

**Comment by kklash** [comment]
Needs rebase

**Comment by ChALkeR** [comment]
Rebased

**Comment by ChALkeR** [comment]
Undid an accidental squash && force pushed, no code changes.

**Review by kklash — APPROVED** [review]
I can't pretend to understand everything this is doing, but since all tests are passing, and for the sake of expediency, utACK

**Pull request merged**
