### PR TITLE
Add depth safeguard checks

### PR DESCRIPTION
**Pull request by ChALkeR**
This is a safeguard against an error behind #66.
It ensures that all independent checks are on the same depth level and one does not affect another.

Only way to get around this is early return, which can happen only in `error` and validation fail.

While this doesn't inspect the code and instead just inspects how many `}` are needed at the end, it's still safe, as if more nesting is involved and `indent` is not increased, the function would just fail to parse.

### CODE REVIEW

**Review by kklash — APPROVED** [review]
Nice! utACK

**Comment by kklash** [comment]
@ChALkeR we could probably use some unit tests for this one. Is that why it's in draft state?

**Comment by ChALkeR** [comment]
I don't think this is coverable by unit tests, there should be no way to trigger those errors.
Those are safeguards against bugs in the code, not in the schema.

It's a draft because I now think that perhaps I could remove the indent logic whatsoever.

**Comment by ChALkeR** [comment]
Closing if favor of #70.

**Pull request closed without merging**
